config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
  registrations: 'public/registrations',
  sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'guest_sign_in', to: 'public/sessions#guest_sign_in'
    delete 'guest_sign_out', to: 'public/sessions#guest_sign_out'
  end

  # ユーザー側
  scope module: :public do
    root to: "homes#top"
    get 'search' => 'posts#search', as: 'search_posts'
    get 'users/mypage' => 'users#mypage', as: 'mypage'
    get 'users/mypage/edit' => 'users#edit', as: 'edit_mypage'
    patch 'users/mypage' => 'users#update', as: 'update_mypage'
    get 'users/mypage/flowering' => 'users#flowering', as: 'mypage_flowering'
    resources :users, only: [:show]
    resources :posts do
      get 'goodbye', on: :member
      resources :comments, only: [:create, :destroy] do
        resources :reports, only: [:new, :create]
      end
      resource :flowers, only: [:create, :destroy]
      resources :reports, only: [:new, :create]
    end
  end


  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: 'admin/sessions'
  }

  #管理者側
  namespace :admin do
    resources :users, only: [:index, :show, :update]
    resources :posts, only: [:destroy] do
      resources :comments, only: [:destroy]
    end
    resources :messages, only: [:index, :create, :edit, :update, :destroy]
    resources :reports, only: [:index, :show, :update, :destroy] do
      collection do
        delete 'destroy_selected', to: 'reports#destroy_selected'
      end
    end
  end

end

app/models/message.rb
class Message < ApplicationRecord
  validates :message, presence: true, length: { maximum: 50 }

end

app/controllers/admin/messages_controller.rb
class Admin::MessagesController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_message, only: [:show, :edit, :update, :destroy]

  def index
    @message = Message.new
    @messages = Message.all.order(created_at: :desc)
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to admin_messages_path, notice: "登録に成功しました"
    else
      @messages = Message.all.order(created_at: :desc)
      flash.now[:alert] = "登録に失敗しました"
      render :index
    end
  end

  def edit
  end

  def update
    if @message.update(message_params)
      redirect_to admin_messages_path, notice: "更新に成功しました"
    else
      flash.now[:alert] = "更新に失敗しました"
      render :edit
    end
  end

  def destroy
    if @message.destroy
      redirect_to admin_messages_path, notice: "遺言が削除されました"
    else
      flash.now[:alert] = "遺言の削除に失敗しました"
      render :edit
    end
  end

  private

  def message_params
    params.require(:message).permit(:message)
  end

  def ensure_message
    @message = Message.find_by_id(params[:id])
    unless @message
      redirect_to admin_messages_path
    end
  end

end

app/helpers/admin/messages_helper.rb
module Admin::MessagesHelper
end

app/views/admin/messages/_form.html.erb
<%= form_with model: message, url: url do |f| %>
  <%= render 'layouts/error_messages', resource: message %>
  <%= f.text_area :message, class: "form_field", rows: 2, required: true, maxlength: 50 %>
  <%= f.submit submit, class: "submit-btn" %>
<% end %>

app/views/admin/messages/edit.html.erb
<div class="admin-content">
  <h2>遺言編集／削除</h2>
  <div class="post_form">
    <%= render 'form', message: @message, url: admin_message_path(@message), submit: '更新' %>
    <%= link_to 'この遺言を削除', admin_message_path(@message), method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'red-btn' %>
  </div>
</div>

app/views/admin/messages/index.html.erb
<div class="admin-content">
  <h3>遺言登録</h3>
  <div class="post_form">
    <%= render 'form', message: @message, url: admin_messages_path, submit: '登録' %>
  </div>
  <p>遺言はお別れ会ページにてランダムで表示されます。</p>
  <div>
    <table>
      <thead>
        <tr>
          <th>遺言</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @messages.each do |message| %>
          <tr>
            <td><%= message.message %></td>
            <td style="white-space: nowrap;">
              <%= link_to "編集/削除", edit_admin_message_path(message) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>