config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
  registrations: 'public/registrations',
  sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'guest_sign_in', to: 'public/sessions#guest_sign_in'
    delete 'guest_sign_out', to: 'public/sessions#guest_sign_out'
  end

  # ユーザー側
  scope module: :public do
    root to: "homes#top"
    get 'search' => 'posts#search', as: 'search_posts'
    get 'users/mypage' => 'users#mypage', as: 'mypage'
    get 'users/mypage/edit' => 'users#edit', as: 'edit_mypage'
    patch 'users/mypage' => 'users#update', as: 'update_mypage'
    get 'users/mypage/flowering' => 'users#flowering', as: 'mypage_flowering'
    resources :users, only: [:show]
    resources :posts do
      get 'goodbye', on: :member
      resources :comments, only: [:create, :destroy] do
        resources :reports, only: [:new, :create]
      end
      resource :flowers, only: [:create, :destroy]
      resources :reports, only: [:new, :create]
    end
  end


  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: 'admin/sessions'
  }

  #管理者側
  namespace :admin do
    resources :users, only: [:index, :show, :update]
    resources :posts, only: [:destroy] do
      resources :comments, only: [:destroy]
    end
    resources :messages, only: [:index, :create, :edit, :update, :destroy]
    resources :reports, only: [:index, :show, :update, :destroy] do
      collection do
        delete 'destroy_selected', to: 'reports#destroy_selected'
      end
    end
  end

end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  # polymorphic　1つのアソシエーション（関連付け）を複数のモデル間で共有する方法
  # reported_itemはPostモデルとCommentモデルに関連付いている。
  belongs_to :reported_item, polymorphic: true

  validates :reason, presence: true, length: { maximum: 400 }

  enum status: {
  waiting: 0,  # 対応待ち
  keep: 1,     # 保留
  finish: 2    # 対応済み
  }

  # reported_item_typeを日本語に変換するメソッド
  def reported_item_type_ja
    if reported_item_type == "Post"
      "投稿"
    elsif reported_item_type == "Comment"
      "コメント"
    end
  end

end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_report, only: [:show, :update, :destroy]

  def index
    @reports = Report.page(params[:page])
  end

  def show
  end

  def update
    if @report.update(report_params)
      redirect_to admin_report_path(@report), notice: "ステータスが更新されました"
    else
      @report.reload # 更新に失敗した時セレクトボックスの選択状態が変わらないようにするため。
      render :show
    end
  end

  def destroy
    if @report.destroy
      redirect_to admin_reports_path, notice: "通報が削除されました"
    else
      flash.now[:alert] = "通報の削除に失敗しました"
      @reports = Report.page(params[:page])
      render :index
    end
  end

  def destroy_selected
    selected_reports = params[:selected_reports]
    if selected_reports.blank?
      redirect_to admin_reports_path, alert: "通報を選択してください"
    else
      Report.where(id: selected_reports).destroy_all
      redirect_to admin_reports_path, notice: "選択された通報が削除されました"
    end
  end

  private

  def ensure_report
    @report = Report.find_by_id(params[:id])
    unless @report
      redirect_to admin_reports_path
    end
  end

  def report_params
    params.require(:report).permit(:status)
  end
end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/views/admin/reports/index.html.erb
<div class="admin-content">
  <h2>通報一覧</h2>
  <% if @reports.present? %>
    <%= form_with(url: destroy_selected_admin_reports_path, method: :delete,
    data: { confirm: "選択した通報を削除しますか？" }) do |f| %>
      <%= f.submit "選択した通報を削除" %>
      <table>
        <thead>
          <th>種類</th>
          <th>通報理由</th>
          <th>通報者</th>
          <th>ステータス</th>
          <th></th>
          <th></th>
        </thead>
        <tbody>
          <% @reports.each do |report| %>
            <tr>
              <td>
                <%= report.reported_item_type_ja %>
              </td>
              <td>
                <%= link_to report.reason.truncate(20), admin_report_path(report) %>
              </td>
              <td><%= report.user.name.truncate(8) %></td>
              <td>
                <% if report.reported_item.present? %>
                  <%= report.status_i18n %>
                <% else %>
                  削除済
                <% end %>
              </td>
              <td>
                <%= link_to "通報を削除", admin_report_path(report), method: :delete %>
              </td>
              <td>
                <%= check_box_tag 'selected_reports[]', report.id %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
    <%= paginate @reports %>
  <% else %>
    <h3>通報はありません</h3>
  <% end %>
</div>

app/views/admin/reports/show.html.erb
<div class="admin-content">
  <% if @report.reported_item.present? %>
    <h2>通報詳細</h2>
    <div class="report_content">
      <p><strong>通報理由</strong></p>
      <p style="margin-bottom: 10px;"><%= @report.reason %></p>

      <p><strong>通報者</strong></p>
      <p style="margin-bottom: 10px;"><%= link_to @report.user.name, admin_user_path(@report.user) %></p>

      <p><strong>通報日時</strong></p>
      <p style="margin-bottom: 10px;"><%= @report.created_at.strftime('%Y/%m/%d %H:%M') %></p>

      <p style="margin-bottom: 10px;"><strong>対応ステータス:</strong> <%= @report.status_i18n %></p>

      <%= form_with(model: @report, url: admin_report_path(@report)) do |f| %>
        <div class="post_form">
          <%= f.label :status, "ステータスの変更" %>
          <%= f.select :status, Report.statuses.keys.map { |k| [I18n.t("enums.report.status.#{k}"), k] } %>
        </div>
        <div class="form_submit">
          <%= f.submit "更新", class: 'submit-btn' %>
        </div>
      <% end %>
    </div>

    <!-- 通報対象がコメントの場合 -->
    <% if @report.reported_item_type == "Comment" %>
      <div class="report_content">
        <p><strong>コメント内容</strong></p>
        <p style="margin-bottom: 10px;"><%= @report.reported_item.comment %></p>
        <p><strong>コメントした人</strong></p>
        <p><%= link_to @report.reported_item.user.name, admin_user_path(@report.reported_item.user) %></p>
      </div>
      <%= link_to '該当コメントをされた投稿へ', post_path(@report.reported_item.post), class: "red-btn" %>
    <!-- 通報対象が投稿の場合 -->
    <% elsif @report.reported_item_type == "Post" %>
      <div class="post-detail">
        <div class="post-detail__image">
          <%= image_tag @report.reported_item.get_image(700, 700) %>
        </div>
        <div class="post-detail__content">
          <h2 class="post-detail__title"><%= @report.reported_item.title %></h2>
          <p><strong>別れの言葉:</strong> <%= @report.reported_item.body %></p>
          <p><strong>投稿者:</strong> <%= link_to @report.reported_item.user.name, admin_user_path(@report.reported_item.user) %></p>
        </div>
      </div>
      <%= link_to '該当の投稿へ', post_path(@report.reported_item), class: "red-btn" %>
    <% end %>

  <% else %>
    <h2>通報詳細</h2>
    <div class="report_content">
      <h3>通報された<%= @report.reported_item_type_ja %>はすでに削除されました</h3>
      <p><strong>通報理由</strong></p>
      <p style="margin-bottom: 10px;"><%= @report.reason %></p>

      <p><strong>通報者</strong></p>
      <p style="margin-bottom: 10px;"><%= @report.user.name %></p>

      <p><strong>通報日時</strong></p>
      <p style="margin-bottom: 10px;"><%= @report.created_at.strftime('%Y/%m/%d %H:%M') %></p>
    </div>
  <% end %>
</div>