config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
  registrations: 'public/registrations',
  sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'guest_sign_in', to: 'public/sessions#guest_sign_in'
    delete 'guest_sign_out', to: 'public/sessions#guest_sign_out'
  end

  # ユーザー側
  scope module: :public do
    root to: "homes#top"
    get 'search' => 'posts#search', as: 'search_posts'
    get 'users/mypage' => 'users#mypage', as: 'mypage'
    get 'users/mypage/edit' => 'users#edit', as: 'edit_mypage'
    patch 'users/mypage' => 'users#update', as: 'update_mypage'
    get 'users/mypage/flowering' => 'users#flowering', as: 'mypage_flowering'
    resources :users, only: [:show]
    resources :posts do
      get 'goodbye', on: :member
      resources :comments, only: [:create, :destroy] do
        resources :reports, only: [:new, :create]
      end
      resource :flowers, only: [:create, :destroy]
      resources :reports, only: [:new, :create]
    end
  end


  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: 'admin/sessions'
  }

  #管理者側
  namespace :admin do
    resources :users, only: [:index, :show, :update]
    resources :posts, only: [:destroy] do
      resources :comments, only: [:destroy]
    end
    resources :messages, only: [:index, :create, :edit, :update, :destroy]
    resources :reports, only: [:index, :show, :update, :destroy] do
      collection do
        delete 'destroy_selected', to: 'reports#destroy_selected'
      end
    end
  end

end

app/views/layouts/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <%= I18n.t("errors.messages.not_saved",
               count: resource.errors.count,
               resource: resource.class.model_name.human.downcase)
     %>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_index.html.erb
<div class="post-list">
  <% posts.each do |post| %>
    <%= link_to post_path(post.id), class: 'post-list__link' do %>
      <div class="post-list__item">
        <%= image_tag post.get_image(400, 400) %>
        <h4 class="post-list__title">
          <% if !post.is_public? %>
            <i class="fas fa-lock"></i>
          <% end %>
          <%= post.title %>
        </h4>
        <p class="post-list__description"><%= post.body %></p>
      </div>
    <% end %>
  <% end %>
</div>
<div class="post-list__paginate"><%= paginate posts %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>私の物がたり</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <script src="https://kit.fontawesome.com/12827ddbda.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+JP&family=Yusei+Magic&display=swap" rel="stylesheet">
  </head>

  <body>
    <header>
      <div class="header-content">
        <div class="header-logo">
          <%= link_to (admin_signed_in? ? admin_reports_path : root_path ), class: "logo" do %>
            <%= image_tag 'logo.png', alt: '私の物がたり', title: "ホームへ" %>
          <% end %>
        </div>
          <% if admin_signed_in? %>
          <div style="text-align: center; color: red;">
            <h2>管理者ログイン中</h2>
          </div>
        <% end %>
        <nav>
          <ul>
            <% if admin_signed_in? %>
              <li><%= link_to '通報一覧',  admin_reports_path %></li>
              <li><%= link_to '会員一覧',  admin_users_path %></li>
              <li><%= link_to '遺言登録',  admin_messages_path %></li>
              <li><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %></li>
            <% elsif user_signed_in? %>
              <li class="<%= 'active' if current_page?(posts_path) %>">
                <%= link_to 'みんなの投稿', posts_path %>
              </li>
              <li class="<%= 'active' if current_page?(new_post_path) %>">
                <%= link_to '投稿する', new_post_path, data: {"turbolinks" => false} %>
              </li>
              <li class="<%= 'active' if current_page?(mypage_path) %>">
                <%= link_to 'マイページ', mypage_path %>
              </li>
              <% if current_user.guest? %>
                <li>
                  <%= link_to 'ログアウト', guest_sign_out_path, method: :delete %>
                </li>
              <% else %>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
              <% end %>
            <% else %>
              <li class="<%= 'active' if current_page?(posts_path) %>">
                <%= link_to 'みんなの投稿', posts_path %>
              </li>
              <li class="<%= 'active' if current_page?(new_user_registration_path) %>">
                <%= link_to '新規登録', new_user_registration_path %>
              </li>
              <li class="<%= 'active' if current_page?(new_user_session_path) %>">
                <%= link_to 'ログイン', new_user_session_path %>
              </li>
              <li>
                <%= link_to 'ゲストログイン', guest_sign_in_path, method: :post %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <main>
      <% flash.each do |message_type, message| %>
        <div class="flash-message <%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </main>
    <footer>&copy; 2023 marin<i class="far fa-star"></i>kato</footer>
  </body>

</html>